version: "3.0"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # - discovery.type=single-node
      - discovery.seed_hosts=['127.0.0.1', '[::1]']
      - xpack.security.enabled=false
      # 跨域 CORS 问题设置 (未验证)
      # - http.cors.enabled=true
      # - http.cors.allow-origin='*'
    volumes:
      - "es-data-es01:/usr/share/elasticsearch/data"
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.6.0
  #   ports:
  #     - "5601:5601"
volumes:
  es-data-es01:
