version: "3.0"
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # ! Dev settings
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - "es-data-es01:/usr/share/elasticsearch/data"
  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.6.0
  #   ports:
  #     - "5601:5601"
volumes:
  es-data-es01:
