version: "3.0"
services:
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticSearch
  elasticSearch:
    container_name: elasticSearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # ! Dev settings
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticSearch_data:/usr/share/elasticsearch/data

volumes:
  elasticSearch_data:
